---
- name: "Настройка всех хостов"
  hosts: all
  roles:
    - common
    - docker
    - gluster

- name: "Поднимаем Nginx и registry"
  hosts: gateway
  roles:
    - registry
    - nginx

- name: "Поднимаем mysql"
  hosts: db
  roles:
    - mysql

- name: "Поднимаем wordpress"
  hosts: wordpress
  roles:
    - wordpress

- name: "Конфигурирования Gateway"
  hosts: gateway
  roles:
    - firewall

- name: "Разворачиваем Kubernetes"
  hosts: k8s-master, workers
  roles:
    - k8s

- name: "Деплой сервисов"
  hosts: k8s-master
  roles:
    - k8s-registry-deploy
    - k8s-mysql-deploy
    - k8s-wordpress-deploy
    - k8s-nginx-deploy
