# Установка сервиса на Centos
---
- name: "Добавляем репозиторий Gluster"
  yum_repository:
    name: "{{ item['name'] }}"
    description: "{{ item['describe'] }}"
    baseurl: "{{ item['repository'] }}"
    gpgcheck: "{{ item['gpgcheck'] | d('true') }}"
    gpgkey: "{{ item['gpgkey'] }}"
    enabled: "{{ item['enabled'] | d('true') }}"
  loop: "{{ gluster_centos_repo_cfg }}"
  when:
    - ansible_os_family == "RedHat"
  tags:
    - gluster
    - gluster-brick-centos

- name: "Устанавливаем gluster на Centos"
  yum:
    name: "{{ gluster_pkgs_install }}"
    state: present
  when:
    - ansible_os_family == "RedHat"
  tags:
    - gluster
    - gluster-brick-centos

- name: "Запуск сервиса Gluster"
  systemd:
    name: "{{ item['name'] }}"
    state: "{{ item['state'] }}"
    enabled: "{{ item['enabled'] }}"
  loop: "{{ gluster_services_list }}"
  when:
    - ansible_os_family == "RedHat"
  tags:
    - gluster
    - gluster-brick-centos
