# Деплой wordpress как 2 реплики
---
- name: "Создание директории для манифестов"
  file:
    path: "{{ item['path'] }}"
    mode: "{{ item['mode'] | d('0744') }}"
    state: "directory"
    recurse: true
  loop:
    - { path: "{{ k8s_wordpress_manifests_dir }}" }
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy

- name: "Создание директории для хранения статики"
  file:
    path: "{{ item['path'] }}"
    mode: "{{ item['mode'] | d('0744') }}"
    state: "directory"
  loop:
    - { path: "{{ k8s_wordpress_hostdir }}" }
  delegate_to: "{{ item }}"
  with_items: "{{ groups['workers'] }}"
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy

- name: "Создание Namespace"
  kubernetes.core.k8s:
    name: "{{ k8s_wordpress_cfg['namespase'] }}"
    api_version: "v1"
    kind: "Namespace"
    state: present
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy

- name: "Перенос манифестов на мастер ноду"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: "{{ item['owner'] | d('root') }}"
    group: "{{ item['group'] | d('root') }}"
    mode: "{{ item['mode'] | d('0644') }}"
  loop:
    - { src: "opt/manifests/wordpress/wordpress-deploy.yml.j2", dest: "{{ k8s_wordpress_manifests_dir }}/wordpress-deploy.yml"}
    - { src: "opt/manifests/wordpress/wordpress-secrets.yaml.j2", dest: "{{ k8s_wordpress_manifests_dir }}/wordpress-secrets.yaml"}
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy

- name: "Деплой манифестов Nginx"
  kubernetes.core.k8s:
    src: "{{ item }}"
    state: present
  loop: "{{ lookup('fileglob', k8s_wordpress_manifests_dir + '/*.yaml', wantlist=true) }}"
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy
