# Деплой wordpress как 2 реплики
---
- name: "Создание директории для манифестов"
  file:
    path: "{{ item['path'] }}"
    mode: "{{ item['mode'] | d('0744') }}"
    state: "directory"
    recurse: true
  loop:
    - { path: "{{ k8s_wordpress_manifests_dir }}" }
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy

- name: "Создание директории для хранения статики"
  file:
    path: "{{ k8s_wordpress_hostdir }}"
    mode: '0744'
    state: "directory"
  delegate_to: "{{ item }}"
  loop: "{{ groups['workers'] }}"
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy

- name: "Создание Namespace"
  kubernetes.core.k8s:
    name: "{{ k8s_wordpress_cfg['namespace'] }}"
    api_version: "v1"
    kind: "Namespace"
    state: present
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy

- name: "Перенос манифестов на мастер ноду"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: "{{ item['owner'] | d('root') }}"
    group: "{{ item['group'] | d('root') }}"
    mode: "{{ item['mode'] | d('0644') }}"
  loop:
    - { src: "opt/manifests/wordpress/wordpress-deploy.yaml.j2", dest: "{{ k8s_wordpress_manifests_dir }}/wordpress-deploy.yaml"}
    - { src: "opt/manifests/wordpress/wordpress-secrets.yaml.j2", dest: "{{ k8s_wordpress_manifests_dir }}/wordpress-secrets.yaml"}
    - { src: "opt/manifests/wordpress/wordpress-deploy-service.yaml.j2", dest: "{{ k8s_wordpress_manifests_dir }}/wordpress-deploy-service.yaml"}
    - { src: "opt/manifests/wordpress/wordpress-deploy-configmap.yaml.j2", dest: "{{ k8s_wordpress_manifests_dir }}/wordpress-deploy-configmap.yaml"}
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy

- name: "Деплой манифестов Wordpress"
  kubernetes.core.k8s:
    src: "{{ k8s_wordpress_manifests_dir }}/{{ item }}"
    state: present
  loop: "{{ k8s_wordpress_manifests }}"
  delegate_to: "{{ groups['k8s-master'][0] }}"
  when:
    - ansible_os_family == "Debian"
  tags:
    - k8s-wordpress-deploy
