# Подготовка ОС перед установкой k8s
---
- name: "Выключаем Swap"
  command: "swapoff -a"
  tags:
    - k8s
    - k8s-setup

- name: "Исключаем swap из fstab" # Может и не заработать, проверить ОТКЛЮЧИЛСЯ ИЛИ НЕТ
  mount:
    name: "{{ item['name'] }}"
    fstype: "{{ item['fstype'] }}"
    state: "{{ item['state'] | d('absent')}}"
  loop:
    - {{ name: "swap", fstype: "swap" }}
  tags:
    - k8s
    - k8s-setup

- name: "Применяем модули ядра"
  community.general.modprobe:
    name: "{{ item['name'] }}"
    state: "{{ item['state'] | d('present') }}"
    persistent: "{{ item['persistent'] | d('present') }}"
  loop: "{{ k8s_modules }}"
  tags:
    - k8s
    - k8s-setup

- name: "Применяем параметры ядра"
  ansible.posix.sysctl:
    name: "{{ item['name'] }}"
    value: "{{ item['value'] }}"
    state: "{{ item['state'] | d('present') }}"
    reload: true
  loop: "{{ k8s_sysctl }}"
  tags:
    - k8s
    - k8s-setup
