# Переменные для k8s
---
k8s_config:
  cfg_file: "/etc/kubernetes/admin.conf"
  cfg_file_workers: "/etc/kubernetes/kubelet.conf"
  pod_network: '10.244.0.0/16'
  connect_str: "kubeadm token create --print-join-command"
  join_cmd_path: "/tmp/k8s_join_command.sh"
  network_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
  network_path: "/tmp/kube-flannel.yml"

# Установка лейблов на воркер ноды
k8s_worker_label:
  - { name: "centosvm", role: "front" }
  - { name: "ubuntuvm", role: "back" }
