 # Переменные подготовки ОС
---
k8s_modules:
  - "br_netfilter"
  - "overlay"

k8s_sysctl:
  - { name: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
  - { name: "net.bridge.bridge-nf-call-iptables", value: 1 }
  - { name: "net.ipv4.ip_forward", value: 1 }
