# Переменные для k8s
---
k8s_config:
  cfg_file: "/etc/kubernetes/admin.conf"
  pod_network: '10.244.0.0/16'
  connect_str: "kubeadm token create --print-join-command"
  network_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
  config_dir: "/home/master/.kube"
  copy_config_dir: "/home/master/.kube/config"

k8s_worker_label:
  - { name: "centosvm", role: "front" }
  - { name: "ubuntuvm", role: "back" }
