# Переменные Ubuntu
---
docker_unbuntu_install_pkgs:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_ubuntu_gpgkey: "https://download.docker.com/linux/ubuntu/gpg"

# Валидность кеша
docker_cache_valid_time: '86400'

# Docker репозиторий ubuntu
docker_ubuntu_repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
