# Установка Kubernetes на Centos
---
- name: "Добавляем репозиторий Kubernetes"
  yum_repository:
    name: "{{ item['name'] }}"
    description: "{{ item['describe'] }}"
    baseurl: "{{ item['repository'] }}"
    gpgkey: "{{ item['gpgkey'] }}"
    gpgcheck: "{{ item['gpgcheck'] | d('true') }}"
    enabled: "{{ item['enabled'] | d('true') }}"
  loop:
    - "{{ k8s_centos_repo_cfg }}"
  when:
    - ansible_os_family == "RedHat"
  tags:
    - k8s
    - k8s-centos-install

- name: "Устанавливаем пакеты K8s"
  yum:
    name: "{{ k8s_install_pkgs }}"
    state: present
    disable_excludes: "kubernetes"
  when:
    - ansible_os_family == "RedHat"
  tags:
    - k8s
    - k8s-centos-install

- name: "Блокируем обновления kubelet, kubeadm, kubectl"
  lineinfile:
    path: "{{ item['path'] }}"
    line: "{{ item['line'] }}"
    insertafter: "EOF"
    create: true
  loop:
    - { path: "/etc/yum.conf", line: "exclude={{ k8s_hold_pkgs | join(' ') }}" }
  when:
    - ansible_os_family == "RedHat"
  tags:
    - k8s
    - k8s-centos-install

- name: "Создание необходимых директорий"
  file:
    path: "{{ item['path'] }}"
    mode: "{{ item['mode'] | d('0744') }}"
    owner: "{{ item['owner'] | d('root') }}"
    group: "{{ item['group'] | d('root') }}"
    state: "directory"
  loop:
    - { path: "{{ k8s_centos_containerd_cfg['conf_dir'] }}" }
  when:
    - ansible_os_family == "RedHat"
  tags:
    - k8s
    - k8s-centos-install

- name: "Копирование настроек containerd"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: "{{ item['owner'] | d('root') }}"
    group: "{{ item['group'] | d('root') }}"
    mode: "{{ item['mode'] | d('0644') }}"
  loop:
    - { src: "etc/containerd/config.toml.j2", dest: "{{ k8s_centos_containerd_cfg['conf_file'] }}" }
  when:
    - ansible_os_family == "RedHat"
  tags:
    - k8s
    - k8s-centos-install

- name: "Запуск сервиса kubelet и containerd"
  systemd:
    name: "{{ item['name'] }}"
    state: "{{ item['state'] | d('started') }}"
    enabled: "{{ item['enabled'] }}"
  loop: "{{ k8s_services_list }}"
  when:
    - ansible_os_family == "RedHat"
  tags:
    - k8s
    - k8s-centos-install
