# Переменные для Nginx
---
k8s_nginx_deploy_manifests_dir: "/opt/manifests/nginx"

k8s_nginx_static_dir: "/mnt/gluster/nginx/html"

k8s_nginx_deploy_manifests:
  - nginx-namespace.yaml
  - nginx-configmap.yaml
  - nginx-secret.yaml
  - nginx-deploy.yaml
  - nginx-service.yaml


k8s_nginx_deploy_config:
  name: "nginx"
  image: "nginx"
  tag: '1.27.4'

k8s_nginx_deploy_cfg:
  name: "nginx"
  namespace: "nginx" # Тестим 3 разных Namespace
  replicas: '1'
  config_name: "nginx-config"
  configmap_name: "nginx-config"
  nodeport: '31080'
  service_type: "NodePort"
  service_name: "nginxwp"
  protocol: "TCP"
  targetPort: '443'
  deploy_port: '443'
  nginx_node: "front"
  secret_file_name: "nginx-ssl"
  secret_name: "nginx-certs"
  wp_ingress_name: "wordpress-ingress"

k8s_nginx_registry_cfg:
  service_name: "registry"
  namespace: "registry"

k8s_nginx_wordpress_cfg:
  service_name: "wordpress-service"
  namespace: "wordpress"

# k8s_nginx_wordpress_service: "wordpress-service"
