# Переменные депллоя Wordpress
---
k8s_wordpress_hostdir: "/mnt/gluster/wordpress"

k8s_wordpress_manifests_dir: "/opt/manifests/wordpress"

k8s_wordpress_deploy_mysql_service: "mysql-service"

k8s_wordpress_container_config:
  name: "wordpress"
  image: "wordpress"
  tag: '6.7'

k8s_wordpress_cfg:
  name: "wordpress"
  namespace: "wordpress"
  service_name: "wordpress-service"
  secret_name: "wordpress-secrets"
  port: '80'
  targetport: '80'
  deploy_name: "wordpress"
  replicas: '1' # ТЕСТ ИСПРАВИТЬ на 2!!!!
  protocol: "TCP"
  service_type: "ClusterIP"
  storage_name: "wordpress-storage"
  db_host: "mysql-service"
  configmap_name: "wp-config"
  config_name: "wps-conf"

k8s_wordpress_manifests:
  - wordpress-secrets.yaml
  - wordpress-deploy.yaml
  - wordpress-deploy-service.yaml
  - wordpress-deploy-configmap.yaml
